[package]
name = "yezi-buddy"
readme = "README.md"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rand_pcg = "0.10"
sha2 = "0.11"
thiserror.workspace = true
rand = "0.10"
ratatui-core.workspace = true
