[package]
name = "yezi-data"
readme = "README.md"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
yaml_serde.workspace = true
thiserror.workspace = true
ulid.workspace = true
serde-inline-default = "1.0.2"
handlebars = "6.4"
