[alias]
md = ["mdbook", "build"]

dbg = ["run",  "-p", "yezi-dbg"]
dev = ["run", "-p", "yezi-dev", "--", "jump"]

[build]
rustdocflags = ["--document-private-items"]

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
