[package]
name = "yezi-fsrs"
readme = "README.md"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fsrs = "6.6"
chrono = "0.4"
ulid = { workspace = true }
diesel = { workspace = true }
libsqlite3-sys = { workspace = true }
thiserror = { workspace = true }
