[package]
name = "yezi-dbg"
readme = "README.md"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
yezi-data = { workspace = true }
yezi-buddy = { workspace = true }
yezi-cfg = { workspace = true }
