[package]
name = "yezi"
readme = "README.md"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
yezi-tui = { workspace = true }

[features]
default = ["dev"]
dev = ["yezi-tui/dev"]
portable = ["yezi-tui/portable"]
install = ["yezi-tui/install"]